users:
  - name: root
    home: /root
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

nix_users:
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

nvm_users:
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

gnome_extension_users:
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

uv_users:
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

xonsh_users:
  - name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

docker_users:
  - "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

git_users:
  - name: kamil
    home: /home/kamil

git_user_name: "Kamil Herbetko"
git_user_email: "herbetko.kamil@gmail.com"

git_core_editor: "hx"

git_extra_config:
  pull.rebase: "false"
  push.autoSetupRemote: "true"
  fetch.prune: "true"

ufw_allow_ssh: true
ufw_ssh_port: 22

ufw_allowed_tcp_ports:
  - 80
  - 443
  - 3000

ufw_allowed_services:
  - OpenSSH
