- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: "{{ ufw_ssh_port }}"
    proto: tcp
  when: ufw_allow_ssh

- name: Allow TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_tcp_ports }}"

- name: Allow UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ ufw_allowed_udp_ports }}"

- name: Allow UFW services
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
  loop: "{{ ufw_allowed_services }}"

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_default_incoming_policy }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_default_outgoing_policy }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    logging: "{{ ufw_logging }}"
  when: ufw_enabled
